---
header:
  teaser: https://raw.githubusercontent.com/commonhaus/artwork/main/foundation/brand/svg/CF_icon_default.svg
---
# JBang moving into CommonHaus Foundation
:page-tagline: JBang is part of the founding projects for the new open source foundation CommonHaus 
:page-category : learn
:page-tags : [jbang]
:page-author : Max Rydahl Andersen
:page-bgcolor: ff5a71
:page-keywords: jbang foundation

ifdef::env-github,env-browser,env-vscode[:imagesdir: ../images]

JBang and its associated projects is joining as a founding project of the https://www.commonhaus.org/[CommonHaus foundation]. 

image::https://raw.githubusercontent.com/commonhaus/artwork/main/foundation/brand/svg/CF_icon_default.svg[width=50%]

CommonHaus is a brand new foundation which focus is on providing a independent home for projects like JBang that are funded by independents and with room for project indivduality.

Other founding projects are https://in.relation.to/2024/04/09/hibernate-to-commonhaus/[Hibernate], https://github.com/FasterXML/jackson[Jackson], https://docs.openrewrite.org/[OpenRewrite], https://andresalmiray.com/jreleaser-joins-commonhaus-foundation/[JReleaser] & https://morphia.dev/[Morphia]. 

== Why JBang in a foundation?

The decision to include JBang in a foundation stems from a desire to ensure its long-term sustainability and growth. Being part of a foundation, especially CommonHaus, provides JBang with a stable, independent home that supports its development and promotes collaboration. This move also opens up new opportunities for funding and contributions, further securing the project's future and fostering an environment where JBang can thrive alongside other like minded open-source projects.

== Why CommonHaus?

The https://www.commonhaus.org/about/#our-guiding-principles[guiding principles] of CommonHaus summarizes it well:

* Honor project and community identity
* Offer guidance and support instead of imposing mandates
* Maintain transparency in all of our actions
* Encourage long-term thinking for sustained project impact

These are important things for JBang - having a place to be hosted for ensuring continuity while still allowing individuality.

== What does it mean for users?

JBang will stay JBang - if you as a user notices it has moved I will be surprised.

Maybe the about text of the CLI will change; that is about it.

== What does it mean for contributors?

The exact onboarding implication is still being defined, but it is expected to have minimal impact as we do most of the recommended things anyways.

== What's next?

Try out https://jbang.dev/downloads[JBang] if you haven't already. If you see something that could need improvement or have a question join the development on https://github.com/jbangdev[GitHub], open issues and discussions and lets help make Java truly available to anyone
.

Have fun!
