---
header:
  teaser: jbanghublaunch.webp
---
# Introducing jbanghub
:page-tagline: jbanghub - a community place for Java with JBang
:page-category : learn
:page-tags : [jbang]
:page-author : Max Rydahl Andersen
:page-bgcolor: ff5a71
:page-keywords: jbang java

ifdef::env-github,env-browser,env-vscode[:imagesdir: ../images]

Today we are introducing https://github.com/jbanghub[JBangHub]!

JBang always allowed everyone easily make their own java/kotlin/groovy/etc. command line tools available in a jbang catalog. All it takes is that you make a jbang-catalog in your project, organization or website.

This is what makes things like `jbang jreleaser@jreleaser` and `jbang minecraft-server@microsoft` possible with minimal effort.

These can then be called as-is or even installed using `jbang app install` making them available in your PATH directly.

Many already added lots of catalogs and they are visible on the https://www.jbang.dev/appstore/[JBang AppStore], readily available to be used from anywhere with JBang available. 

This is anywhere you can run java including from https://www.jbang.dev/learn/jbang-npm/[javascript] and https://www.jbang.dev/learn/python-with-jbang/[python] - yes, even Jupyter Notebooks can access Java with JBang.

To make it even easier and make it possible for anyone to make their favourite tools available under a nice and simple name we are introducing https://github.com/jbangdev[JBangHub], a GitHub organization where we invite everyone to contribute scripts and tools they would like to see easily available.

JBangHub is there to let anyone help any project become more easily accessible and also to show how little effort is needed to setup and maintain a jbang-catalog.

== Automatic dependency updates

We made a `jbang-catalog` template available that setups of a jbang-catalog with automatic renovate bot based updates.

All repos in JBangHub uses this to ensure any Maven referenced artifacts will get updates, but anyone can use this in their own jbang-catalog outside JBangHub too.

Just start it using `jbang init -t jbang-catalog <reponame>` and add aliases to your jbang-catalog.

== Default Catalog 

The latest release (0.116) of JBang adds `jbanghub` as a default jbang catalog so when you do `jbang catalog list` you get something like:

image:jbangcataloglist.svg[]

This list is not intended to be *every* jbang-catalog on the planet - but more a teaser on what is available out there. We encourage and accept edits/updates to that list at https://github.com/jbanghub/jbang-catalog.

e
Have fun!
